name: frontend-prod

on:
  push:
    branches:
      - main
    paths:
      - app/**
      - .github/workflows/frontend-prod.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        working-directory: './app'
        run: yarn

      - working-directory: './app'
        run: yarn build

      - working-directory: './app'
        run: aws s3 sync build/ s3://churras-planner --delete --cache-control max-age=31536000,public
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
